version: '3'

services:

  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
      
  postgres:
    image: 'postgres:latest'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_NAME: ${DATABASE_NAME}
    container_name: migration-routes-db
    shm_size: 128mb

    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  redis: